In [1]:

import twint
import csv
import pandas as pd
import time

In [ ]:

# setup twint
c = twint.Config()
c.Search = "Biden pardons marijuana"
c.Store_csv = True
c.Output = "biden_pardons_marijuana.csv"
c.Since = "2022-10-1"
c.Until = "2022-10-11"
c.Hide_output = True

# run search
twint.run.Search(c)

In [6]:
# read csv file
df = pd.read_csv("biden_pardons_marijuana.csv")

In [7]:
# make a dataframe 
df = pd.DataFrame(df)

In [8]:
display(df.head(10))

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1579258785058914305,1579258785058914305,2022-10-09 19:53:30 Eastern Daylight Time,2022-10-09,19:53:30,-400,1099281359397421056,aljacobrds,rds-AlJacob,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
1,1579258508704645121,1579258508704645121,2022-10-09 19:52:24 Eastern Daylight Time,2022-10-09,19:52:24,-400,616996381,stevel202,SteveL,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
2,1579256733393788928,1579256733393788928,2022-10-09 19:45:21 Eastern Daylight Time,2022-10-09,19:45:21,-400,1359638722761818113,vonsavagemedia,Tz Von Savage,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
3,1579254493941624833,1579254493941624833,2022-10-09 19:36:27 Eastern Daylight Time,2022-10-09,19:36:27,-400,1552359542,german_dictator,Captor Zone,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
4,1579254460269793281,1579254460269793281,2022-10-09 19:36:19 Eastern Daylight Time,2022-10-09,19:36:19,-400,244775645,grbusinaro,"Gerald Businaro, RPh",NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
5,1579253212237901824,1579253212237901824,2022-10-09 19:31:21 Eastern Daylight Time,2022-10-09,19:31:21,-400,842050030970277888,suevelez19,Sue Velez,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
6,1579253149205811200,1579253149205811200,2022-10-09 19:31:06 Eastern Daylight Time,2022-10-09,19:31:06,-400,1297574551216414720,internationaln0,International News USA,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
7,1579252605720530944,1579252605720530944,2022-10-09 19:28:56 Eastern Daylight Time,2022-10-09,19:28:56,-400,355063782,rbeestweets,rbee,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
8,1579251548298747904,1579251548298747904,2022-10-09 19:24:44 Eastern Daylight Time,2022-10-09,19:24:44,-400,926542105287069696,joeontheloose,JOE ðŸ‡¦ðŸ‡º,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
9,1579248282366226432,1579248282366226432,2022-10-09 19:11:46 Eastern Daylight Time,2022-10-09,19:11:46,-400,1362507448897179651,_hermetic9,âšš HermeticðŸ‡µðŸ‡·ðŸ‡¨ðŸ‡®ðŸ‡µðŸ‡¸,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN

In [ ]:
# drop duplicates
df.drop_duplicates(subset ="tweet", keep = False, inplace = True)

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1579258785058914305,1579258785058914305,2022-10-09 19:53:30 Eastern Daylight Time,2022-10-09,19:53:30,-400,1099281359397421056,aljacobrds,rds-AlJacob,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
1,1579258508704645121,1579258508704645121,2022-10-09 19:52:24 Eastern Daylight Time,2022-10-09,19:52:24,-400,616996381,stevel202,SteveL,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
2,1579256733393788928,1579256733393788928,2022-10-09 19:45:21 Eastern Daylight Time,2022-10-09,19:45:21,-400,1359638722761818113,vonsavagemedia,Tz Von Savage,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
3,1579254493941624833,1579254493941624833,2022-10-09 19:36:27 Eastern Daylight Time,2022-10-09,19:36:27,-400,1552359542,german_dictator,Captor Zone,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
4,1579254460269793281,1579254460269793281,2022-10-09 19:36:19 Eastern Daylight Time,2022-10-09,19:36:19,-400,244775645,grbusinaro,"Gerald Businaro, RPh",NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
5,1579253212237901824,1579253212237901824,2022-10-09 19:31:21 Eastern Daylight Time,2022-10-09,19:31:21,-400,842050030970277888,suevelez19,Sue Velez,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
6,1579253149205811200,1579253149205811200,2022-10-09 19:31:06 Eastern Daylight Time,2022-10-09,19:31:06,-400,1297574551216414720,internationaln0,International News USA,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
7,1579252605720530944,1579252605720530944,2022-10-09 19:28:56 Eastern Daylight Time,2022-10-09,19:28:56,-400,355063782,rbeestweets,rbee,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
8,1579251548298747904,1579251548298747904,2022-10-09 19:24:44 Eastern Daylight Time,2022-10-09,19:24:44,-400,926542105287069696,joeontheloose,JOE ðŸ‡¦ðŸ‡º,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
9,1579248282366226432,1579248282366226432,2022-10-09 19:11:46 Eastern Daylight Time,2022-10-09,19:11:46,-400,1362507448897179651,_hermetic9,âšš HermeticðŸ‡µðŸ‡·ðŸ‡¨ðŸ‡®ðŸ‡µðŸ‡¸,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN